### ISSUE TITLE
Error with generated grpc files

### ISSUE THREAD

**Issue by MikhailFDone** [userver-framework/pg_grpc_service_template#11]
There is a problem with adding proto files that depend on other proto files.
If you add to CMakeLists.txt

```
add_grpc_library(${PROJECT_NAME}_proto
 INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/proto/handlers"
 PROTOS
 handlers/hello.proto
 handlers/hello2.proto)
```

hello2.proto may look like this, for example:

```
syntax = "proto3";
package handlers.api;
import "hello.proto";
message Hello2 {
 HelloResponse text = 1;
}
```

after that, the generated files are placed in proto/ and not in proto/handlers/
specifying SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/proto" does not help

**Comment by alexiprof** [comment]
It was fixed.
